# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kiwifs < Formula
  desc "Markdown filesystem for agents and teams"
  homepage "https://kiwifs.com"
  version "0.18.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kiwifs/kiwifs/releases/download/v0.18.0/kiwifs_darwin_amd64.tar.gz"
      sha256 "1275534629dd62a8b98f4f563013dd47937eff0ad4daa219018cc96c66615157"

      define_method(:install) do
        bin.install "kiwifs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kiwifs/kiwifs/releases/download/v0.18.0/kiwifs_darwin_arm64.tar.gz"
      sha256 "765a3ed80f2d6d244b6f0655f2d9b666bd96e398793c95b374521e57903cb15f"

      define_method(:install) do
        bin.install "kiwifs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kiwifs/kiwifs/releases/download/v0.18.0/kiwifs_linux_amd64.tar.gz"
      sha256 "a3d00c2fe457b3d21583d77c1ec4b857736fa3624ebe98af4e8741ccb48d3eb3"
      define_method(:install) do
        bin.install "kiwifs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kiwifs/kiwifs/releases/download/v0.18.0/kiwifs_linux_arm64.tar.gz"
      sha256 "8c6f7d91bbd0ffc2c3d7eb898c2663caee7cf7f1d1866951bb500f3b8da9997a"
      define_method(:install) do
        bin.install "kiwifs"
      end
    end
  end

  test do
    system "#{bin}/kiwifs", "--version"
  end
end
