# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kiwifs < Formula
  desc "Markdown filesystem for agents and teams"
  homepage "https://kiwifs.com"
  version "0.19.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kiwifs/kiwifs/releases/download/v0.19.0/kiwifs_darwin_amd64.tar.gz"
      sha256 "3c5b16067a151f5e9cfad4333bcc8dfb8b9f21aca36965a298831c8d83f7f80d"

      define_method(:install) do
        bin.install "kiwifs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kiwifs/kiwifs/releases/download/v0.19.0/kiwifs_darwin_arm64.tar.gz"
      sha256 "7dd359702c673dad217540325dbc424188ec172d1cd7ef8b578bc5d72a4eb818"

      define_method(:install) do
        bin.install "kiwifs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kiwifs/kiwifs/releases/download/v0.19.0/kiwifs_linux_amd64.tar.gz"
      sha256 "cd0177b7974a72b6d4fe49c3bf54188600770e67f582eabec77e83d985cbfafd"
      define_method(:install) do
        bin.install "kiwifs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kiwifs/kiwifs/releases/download/v0.19.0/kiwifs_linux_arm64.tar.gz"
      sha256 "ab7974abf11b680503518a55ae0d953d253eb5e81c6576117fcc21c35357e53a"
      define_method(:install) do
        bin.install "kiwifs"
      end
    end
  end

  test do
    system "#{bin}/kiwifs", "--version"
  end
end
